// const data = await SDK
  // .getAssetPlatforms({});
  // .getCategories();
  // .getCategoriesWithMarketData({});
  // .getCoinList();
  // .getCoinMarketList({ vs_currency: "usd", ids: "bitcoin,ethereum" });
  // .getCoinDataById({ id: "bitcoin" });
  // .getCoinTickersById({ id: "bitcoin" });
  // .getCoinHistoricalDataById({ id: "bitcoin", date: "30-12-2024" });
  // .getCoinHistoricalChartDataById({ id: "bitcoin", vs_currency: "usd", days: "1", interval: "daily" });
  // .getCoinHistoricalChartDataRangeById({ id: "bitcoin", vs_currency: "usd", from: 1711929600, to: 1712275200 });
  // .getCoinOhlcChartDataById({ id: "bitcoin", vs_currency: "usd", days: 1 });
  // .getCompagniesPublicTreasury({ coin_id: "bitcoin" });
  // .getCoinData({ id: "ethereum", contract_address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" });
  // .getCoinChartData({ id: "ethereum", contract_address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", vs_currency: "usd", days: 1 });
  // .getCoinChartDataWithinTimeRange({ id: "ethereum", contract_address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", vs_currency: "usd", from: 1711929600, to: 1712275200 });
  // .getDerivativesTickers();
  // .getDerivativesExchanges({order: "name_asc", per_page: 100, page: 1});
  // .getDrerivativesExchangeById({id: "binance_futures", index_tickers: "all"});
  // .getDerivativesExchangesList();
  // .getExchangeRates();
  // .getExchangesWithData({ per_page: 10, page: 1 });
  // .getExchangesList({ status: "active" });
  // .getExchangesId({ id: "binance" });
  // .getExchangesTickersId({ id: "binance", coin_ids: "bitcoin" });
  // .getExchangesVolumeChart({ id: "binance", days: 1 });
  // .getCryptoGlobal();
  // .getDefiGlobal();
  // .getNFTs({order: "h24_volume_usd_asc", per_page: 10, page: 1});
  // .getNFTById({ id: 'pudgy-penguins' });
  // .getNFTByContractAddress({ asset_platform_id: 'ethereum', contract_address: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8' });
  // .getPing();
  // .search({ query: 'bitcoin' });
  // .getCoinPriceByIds({ ids: "bitcoin", vs_currencies: "usd" });
  // .getCoinPriceByTokenAddress({ id: "ethereum", vs_currencies: "usd", contract_addresses: "0x0d8775f648430679a709e98d2b0cb6250d2887ef" });
  // .getSupportedCurrencies();
  // .getTrendingSearchList();
  ;
  // console.log(data);