name: Publish to npm

on:
  push:
    branches:
      - main  # Déclenche l'action quand tu pushes sur la branche principale
  release:
    types:
      - created  # Déclenche aussi quand tu crées une release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
          # scope: "@awsd"  # Remplace par ton scope si ton package est scoped

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Assure-toi que ce script compile ton TypeScript

      - name: Check npm authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
